//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mesnac.Entity {
    using System;
    using System.Xml.Serialization;
    using NBear.Common;
    
    
    [System.SerializableAttribute()]
    public partial class Eqm_bjsparecdArrayList : NBear.Common.EntityArrayList<Mesnac.Entity.Eqm_bjsparecd> {
    }
    
    [System.SerializableAttribute()]
    [NBear.Common.EmbeddedEntityConfigurationAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<EntityConfiguration xmlns:xsd=\"http://w" +
        "ww.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" " +
        "name=\"Mesnac.Entity.Eqm_bjsparecd\" isReadOnly=\"false\" isAutoPreLoad=\"false\" isBa" +
        "tchUpdate=\"false\" isRelation=\"false\" mappingName=\"Eqm_bjsparecd\" batchSize=\"10\">" +
        "\r\n  <Properties>\r\n    <Property name=\"BJ_code\" type=\"System.String\" isInherited=" +
        "\"false\" isReadOnly=\"false\" isCompoundUnit=\"false\" isContained=\"false\" isQuery=\"f" +
        "alse\" isFriendKey=\"false\" isLazyLoad=\"false\" isRelationKey=\"false\" isIndexProper" +
        "ty=\"false\" isIndexPropertyDesc=\"false\" isSerializationIgnore=\"false\" mappingName" +
        "=\"BJ_code\" mappingColumnType=\"System.String\" sqlType=\"varchar(20)\" isPrimaryKey=" +
        "\"true\" isNotNull=\"true\" />\r\n    <Property name=\"BJ_specType\" type=\"System.String" +
        "\" isInherited=\"false\" isReadOnly=\"false\" isCompoundUnit=\"false\" isContained=\"fal" +
        "se\" isQuery=\"false\" isFriendKey=\"false\" isLazyLoad=\"false\" isRelationKey=\"false\"" +
        " isIndexProperty=\"false\" isIndexPropertyDesc=\"false\" isSerializationIgnore=\"fals" +
        "e\" mappingName=\"BJ_specType\" mappingColumnType=\"System.String\" sqlType=\"nvarchar" +
        "(255)\" isPrimaryKey=\"false\" isNotNull=\"false\" />\r\n    <Property name=\"BJ_name\" t" +
        "ype=\"System.String\" isInherited=\"false\" isReadOnly=\"false\" isCompoundUnit=\"false" +
        "\" isContained=\"false\" isQuery=\"false\" isFriendKey=\"false\" isLazyLoad=\"false\" isR" +
        "elationKey=\"false\" isIndexProperty=\"false\" isIndexPropertyDesc=\"false\" isSeriali" +
        "zationIgnore=\"false\" mappingName=\"BJ_name\" mappingColumnType=\"System.String\" sql" +
        "Type=\"nvarchar(50)\" isPrimaryKey=\"false\" isNotNull=\"false\" />\r\n    <Property nam" +
        "e=\"Unit_name\" type=\"System.String\" isInherited=\"false\" sqlDefaultValue=\"\' \'\" isR" +
        "eadOnly=\"false\" isCompoundUnit=\"false\" isContained=\"false\" isQuery=\"false\" isFri" +
        "endKey=\"false\" isLazyLoad=\"false\" isRelationKey=\"false\" isIndexProperty=\"false\" " +
        "isIndexPropertyDesc=\"false\" isSerializationIgnore=\"false\" mappingName=\"Unit_name" +
        "\" mappingColumnType=\"System.String\" sqlType=\"varchar(20)\" isPrimaryKey=\"false\" i" +
        "sNotNull=\"false\" />\r\n    <Property name=\"BJ_tpcode\" type=\"System.String\" isInher" +
        "ited=\"false\" isReadOnly=\"false\" isCompoundUnit=\"false\" isContained=\"false\" isQue" +
        "ry=\"false\" isFriendKey=\"false\" isLazyLoad=\"false\" isRelationKey=\"false\" isIndexP" +
        "roperty=\"false\" isIndexPropertyDesc=\"false\" isSerializationIgnore=\"false\" mappin" +
        "gName=\"BJ_tpcode\" mappingColumnType=\"System.String\" sqlType=\"varchar(20)\" isPrim" +
        "aryKey=\"false\" isNotNull=\"false\" />\r\n    <Property name=\"High_reserve\" type=\"Sys" +
        "tem.Nullable`1[System.Decimal]\" isInherited=\"false\" isReadOnly=\"false\" isCompoun" +
        "dUnit=\"false\" isContained=\"false\" isQuery=\"false\" isFriendKey=\"false\" isLazyLoad" +
        "=\"false\" isRelationKey=\"false\" isIndexProperty=\"false\" isIndexPropertyDesc=\"fals" +
        "e\" isSerializationIgnore=\"false\" mappingName=\"High_reserve\" mappingColumnType=\"S" +
        "ystem.Nullable`1[System.Decimal]\" sqlType=\"decimal\" isPrimaryKey=\"false\" isNotNu" +
        "ll=\"false\" />\r\n    <Property name=\"Low_reserve\" type=\"System.Nullable`1[System.D" +
        "ecimal]\" isInherited=\"false\" isReadOnly=\"false\" isCompoundUnit=\"false\" isContain" +
        "ed=\"false\" isQuery=\"false\" isFriendKey=\"false\" isLazyLoad=\"false\" isRelationKey=" +
        "\"false\" isIndexProperty=\"false\" isIndexPropertyDesc=\"false\" isSerializationIgnor" +
        "e=\"false\" mappingName=\"Low_reserve\" mappingColumnType=\"System.Nullable`1[System." +
        "Decimal]\" sqlType=\"decimal\" isPrimaryKey=\"false\" isNotNull=\"false\" />\r\n    <Prop" +
        "erty name=\"Order_point\" type=\"System.Nullable`1[System.Decimal]\" isInherited=\"fa" +
        "lse\" isReadOnly=\"false\" isCompoundUnit=\"false\" isContained=\"false\" isQuery=\"fals" +
        "e\" isFriendKey=\"false\" isLazyLoad=\"false\" isRelationKey=\"false\" isIndexProperty=" +
        "\"false\" isIndexPropertyDesc=\"false\" isSerializationIgnore=\"false\" mappingName=\"O" +
        "rder_point\" mappingColumnType=\"System.Nullable`1[System.Decimal]\" sqlType=\"decim" +
        "al\" isPrimaryKey=\"false\" isNotNull=\"false\" />\r\n    <Property name=\"High_fund\" ty" +
        "pe=\"System.Nullable`1[System.Decimal]\" isInherited=\"false\" isReadOnly=\"false\" is" +
        "CompoundUnit=\"false\" isContained=\"false\" isQuery=\"false\" isFriendKey=\"false\" isL" +
        "azyLoad=\"false\" isRelationKey=\"false\" isIndexProperty=\"false\" isIndexPropertyDes" +
        "c=\"false\" isSerializationIgnore=\"false\" mappingName=\"High_fund\" mappingColumnTyp" +
        "e=\"System.Nullable`1[System.Decimal]\" sqlType=\"decimal\" isPrimaryKey=\"false\" isN" +
        "otNull=\"false\" />\r\n    <Property name=\"Low_fund\" type=\"System.Nullable`1[System." +
        "Decimal]\" isInherited=\"false\" isReadOnly=\"false\" isCompoundUnit=\"false\" isContai" +
        "ned=\"false\" isQuery=\"false\" isFriendKey=\"false\" isLazyLoad=\"false\" isRelationKey" +
        "=\"false\" isIndexProperty=\"false\" isIndexPropertyDesc=\"false\" isSerializationIgno" +
        "re=\"false\" mappingName=\"Low_fund\" mappingColumnType=\"System.Nullable`1[System.De" +
        "cimal]\" sqlType=\"decimal\" isPrimaryKey=\"false\" isNotNull=\"false\" />\r\n    <Proper" +
        "ty name=\"Pos_code\" type=\"System.String\" isInherited=\"false\" isReadOnly=\"false\" i" +
        "sCompoundUnit=\"false\" isContained=\"false\" isQuery=\"false\" isFriendKey=\"false\" is" +
        "LazyLoad=\"false\" isRelationKey=\"false\" isIndexProperty=\"false\" isIndexPropertyDe" +
        "sc=\"false\" isSerializationIgnore=\"false\" mappingName=\"Pos_code\" mappingColumnTyp" +
        "e=\"System.String\" sqlType=\"varchar(20)\" isPrimaryKey=\"false\" isNotNull=\"false\" /" +
        ">\r\n    <Property name=\"Plan_price\" type=\"System.Nullable`1[System.Decimal]\" isIn" +
        "herited=\"false\" sqlDefaultValue=\"(0.00)\" isReadOnly=\"false\" isCompoundUnit=\"fals" +
        "e\" isContained=\"false\" isQuery=\"false\" isFriendKey=\"false\" isLazyLoad=\"false\" is" +
        "RelationKey=\"false\" isIndexProperty=\"false\" isIndexPropertyDesc=\"false\" isSerial" +
        "izationIgnore=\"false\" mappingName=\"Plan_price\" mappingColumnType=\"System.Nullabl" +
        "e`1[System.Decimal]\" sqlType=\"numeric\" isPrimaryKey=\"false\" isNotNull=\"false\" />" +
        "\r\n    <Property name=\"BJ_Class\" type=\"System.String\" isInherited=\"false\" isReadO" +
        "nly=\"false\" isCompoundUnit=\"false\" isContained=\"false\" isQuery=\"false\" isFriendK" +
        "ey=\"false\" isLazyLoad=\"false\" isRelationKey=\"false\" isIndexProperty=\"false\" isIn" +
        "dexPropertyDesc=\"false\" isSerializationIgnore=\"false\" mappingName=\"BJ_Class\" map" +
        "pingColumnType=\"System.String\" sqlType=\"varchar(10)\" isPrimaryKey=\"false\" isNotN" +
        "ull=\"false\" />\r\n    <Property name=\"Memo\" type=\"System.String\" isInherited=\"fals" +
        "e\" isReadOnly=\"false\" isCompoundUnit=\"false\" isContained=\"false\" isQuery=\"false\"" +
        " isFriendKey=\"false\" isLazyLoad=\"false\" isRelationKey=\"false\" isIndexProperty=\"f" +
        "alse\" isIndexPropertyDesc=\"false\" isSerializationIgnore=\"false\" mappingName=\"Mem" +
        "o\" mappingColumnType=\"System.String\" sqlType=\"varchar(50)\" isPrimaryKey=\"false\" " +
        "isNotNull=\"false\" />\r\n  </Properties>\r\n</EntityConfiguration>")]
    public partial class Eqm_bjsparecd : NBear.Common.Entity {
        
        protected static NBear.Common.EntityConfiguration _Eqm_bjsparecdEntityConfiguration;
        
        protected string _BJ_code;
        
        protected string _BJ_specType;
        
        protected string _BJ_name;
        
        protected string _Unit_name;
        
        protected string _BJ_tpcode;
        
        protected global::System.Decimal? _High_reserve;
        
        protected global::System.Decimal? _Low_reserve;
        
        protected global::System.Decimal? _Order_point;
        
        protected global::System.Decimal? _High_fund;
        
        protected global::System.Decimal? _Low_fund;
        
        protected string _Pos_code;
        
        protected global::System.Decimal? _Plan_price;
        
        protected string _BJ_Class;
        
        protected string _Memo;
        
        public static @__Columns _ = new @__Columns();
        
		public static bool operator ==(global::Mesnac.Entity.Eqm_bjsparecd left, global::Mesnac.Entity.Eqm_bjsparecd right) { return ((object)left) != null ? left.Equals(right) : ((object)right) == null ? true : false; }


		public static bool operator !=(global::Mesnac.Entity.Eqm_bjsparecd left, global::Mesnac.Entity.Eqm_bjsparecd right) { return ((object)left) != null ? !left.Equals(right) : ((object)right) == null ? false : true; }


        
        public string BJ_code {
            get {
                return this._BJ_code;
            }
            set {
                this.OnPropertyChanged("BJ_code", this._BJ_code, value);
                this._BJ_code = value;
            }
        }
        
        public string BJ_specType {
            get {
                return this._BJ_specType;
            }
            set {
                this.OnPropertyChanged("BJ_specType", this._BJ_specType, value);
                this._BJ_specType = value;
            }
        }
        
        public string BJ_name {
            get {
                return this._BJ_name;
            }
            set {
                this.OnPropertyChanged("BJ_name", this._BJ_name, value);
                this._BJ_name = value;
            }
        }
        
        public string Unit_name {
            get {
                return this._Unit_name;
            }
            set {
                this.OnPropertyChanged("Unit_name", this._Unit_name, value);
                this._Unit_name = value;
            }
        }
        
        public string BJ_tpcode {
            get {
                return this._BJ_tpcode;
            }
            set {
                this.OnPropertyChanged("BJ_tpcode", this._BJ_tpcode, value);
                this._BJ_tpcode = value;
            }
        }
        
        public global::System.Decimal? High_reserve {
            get {
                return this._High_reserve;
            }
            set {
                this.OnPropertyChanged("High_reserve", this._High_reserve, value);
                this._High_reserve = value;
            }
        }
        
        public global::System.Decimal? Low_reserve {
            get {
                return this._Low_reserve;
            }
            set {
                this.OnPropertyChanged("Low_reserve", this._Low_reserve, value);
                this._Low_reserve = value;
            }
        }
        
        public global::System.Decimal? Order_point {
            get {
                return this._Order_point;
            }
            set {
                this.OnPropertyChanged("Order_point", this._Order_point, value);
                this._Order_point = value;
            }
        }
        
        public global::System.Decimal? High_fund {
            get {
                return this._High_fund;
            }
            set {
                this.OnPropertyChanged("High_fund", this._High_fund, value);
                this._High_fund = value;
            }
        }
        
        public global::System.Decimal? Low_fund {
            get {
                return this._Low_fund;
            }
            set {
                this.OnPropertyChanged("Low_fund", this._Low_fund, value);
                this._Low_fund = value;
            }
        }
        
        public string Pos_code {
            get {
                return this._Pos_code;
            }
            set {
                this.OnPropertyChanged("Pos_code", this._Pos_code, value);
                this._Pos_code = value;
            }
        }
        
        public global::System.Decimal? Plan_price {
            get {
                return this._Plan_price;
            }
            set {
                this.OnPropertyChanged("Plan_price", this._Plan_price, value);
                this._Plan_price = value;
            }
        }
        
        public string BJ_Class {
            get {
                return this._BJ_Class;
            }
            set {
                this.OnPropertyChanged("BJ_Class", this._BJ_Class, value);
                this._BJ_Class = value;
            }
        }
        
        public string Memo {
            get {
                return this._Memo;
            }
            set {
                this.OnPropertyChanged("Memo", this._Memo, value);
                this._Memo = value;
            }
        }
        
        public override NBear.Common.EntityConfiguration GetEntityConfiguration() {
            if ((Eqm_bjsparecd._Eqm_bjsparecdEntityConfiguration == null)) {
                Eqm_bjsparecd._Eqm_bjsparecdEntityConfiguration = NBear.Common.MetaDataManager.GetEntityConfiguration("Mesnac.Entity.Eqm_bjsparecd");
            }
            return Eqm_bjsparecd._Eqm_bjsparecdEntityConfiguration;
        }
        
        public override void ReloadQueries(bool includeLazyLoadQueries) {
        }
        
        public override object[] GetPropertyValues() {
            return new object[] {
                    this._BJ_code,
                    this._BJ_specType,
                    this._BJ_name,
                    this._Unit_name,
                    this._BJ_tpcode,
                    this._High_reserve,
                    this._Low_reserve,
                    this._Order_point,
                    this._High_fund,
                    this._Low_fund,
                    this._Pos_code,
                    this._Plan_price,
                    this._BJ_Class,
                    this._Memo};
        }
        
        public override void SetPropertyValues(System.Data.IDataReader reader) {
            if ((false == reader.IsDBNull(0))) {
                this._BJ_code = reader.GetString(0);
            }
            if ((false == reader.IsDBNull(1))) {
                this._BJ_specType = reader.GetString(1);
            }
            if ((false == reader.IsDBNull(2))) {
                this._BJ_name = reader.GetString(2);
            }
            if ((false == reader.IsDBNull(3))) {
                this._Unit_name = reader.GetString(3);
            }
            if ((false == reader.IsDBNull(4))) {
                this._BJ_tpcode = reader.GetString(4);
            }
            if ((false == reader.IsDBNull(5))) {
                this._High_reserve = reader.GetDecimal(5);
            }
            if ((false == reader.IsDBNull(6))) {
                this._Low_reserve = reader.GetDecimal(6);
            }
            if ((false == reader.IsDBNull(7))) {
                this._Order_point = reader.GetDecimal(7);
            }
            if ((false == reader.IsDBNull(8))) {
                this._High_fund = reader.GetDecimal(8);
            }
            if ((false == reader.IsDBNull(9))) {
                this._Low_fund = reader.GetDecimal(9);
            }
            if ((false == reader.IsDBNull(10))) {
                this._Pos_code = reader.GetString(10);
            }
            if ((false == reader.IsDBNull(11))) {
                this._Plan_price = reader.GetDecimal(11);
            }
            if ((false == reader.IsDBNull(12))) {
                this._BJ_Class = reader.GetString(12);
            }
            if ((false == reader.IsDBNull(13))) {
                this._Memo = reader.GetString(13);
            }
            this.ReloadQueries(false);
        }
        
        public override void SetPropertyValues(System.Data.DataRow row) {
            if ((false == row.IsNull(0))) {
                this._BJ_code = ((string)(row[0]));
            }
            if ((false == row.IsNull(1))) {
                this._BJ_specType = ((string)(row[1]));
            }
            if ((false == row.IsNull(2))) {
                this._BJ_name = ((string)(row[2]));
            }
            if ((false == row.IsNull(3))) {
                this._Unit_name = ((string)(row[3]));
            }
            if ((false == row.IsNull(4))) {
                this._BJ_tpcode = ((string)(row[4]));
            }
            if ((false == row.IsNull(5))) {
                this._High_reserve = ((System.Nullable<decimal>)(row[5]));
            }
            if ((false == row.IsNull(6))) {
                this._Low_reserve = ((System.Nullable<decimal>)(row[6]));
            }
            if ((false == row.IsNull(7))) {
                this._Order_point = ((System.Nullable<decimal>)(row[7]));
            }
            if ((false == row.IsNull(8))) {
                this._High_fund = ((System.Nullable<decimal>)(row[8]));
            }
            if ((false == row.IsNull(9))) {
                this._Low_fund = ((System.Nullable<decimal>)(row[9]));
            }
            if ((false == row.IsNull(10))) {
                this._Pos_code = ((string)(row[10]));
            }
            if ((false == row.IsNull(11))) {
                this._Plan_price = ((System.Nullable<decimal>)(row[11]));
            }
            if ((false == row.IsNull(12))) {
                this._BJ_Class = ((string)(row[12]));
            }
            if ((false == row.IsNull(13))) {
                this._Memo = ((string)(row[13]));
            }
            this.ReloadQueries(false);
        }
        
        public override int GetHashCode() {
            return base.GetHashCode();
        }
        
        public override bool Equals(object obj) {
            if ((obj == null)) {
                return false;
            }
            if ((false == typeof(global::Mesnac.Entity.Eqm_bjsparecd).IsAssignableFrom(obj.GetType()))) {
                return false;
            }
            if ((((object)(this)) == ((object)(obj)))) {
                return true;
            }
            return ((this.isAttached && ((global::Mesnac.Entity.Eqm_bjsparecd)(obj)).isAttached) 
                        && (this.BJ_code == ((global::Mesnac.Entity.Eqm_bjsparecd)(obj)).BJ_code));
        }
        
        public static @__Columns @__Alias(string aliasName) {
            return new @__Columns(aliasName);
        }
        
        public class @__Columns {
            
            protected string aliasName;
            
            protected NBear.Common.PropertyItem _BJ_code = new NBear.Common.PropertyItem("BJ_code", "Mesnac.Entity.Eqm_bjsparecd");
            
            protected NBear.Common.PropertyItem _BJ_specType = new NBear.Common.PropertyItem("BJ_specType", "Mesnac.Entity.Eqm_bjsparecd");
            
            protected NBear.Common.PropertyItem _BJ_name = new NBear.Common.PropertyItem("BJ_name", "Mesnac.Entity.Eqm_bjsparecd");
            
            protected NBear.Common.PropertyItem _Unit_name = new NBear.Common.PropertyItem("Unit_name", "Mesnac.Entity.Eqm_bjsparecd");
            
            protected NBear.Common.PropertyItem _BJ_tpcode = new NBear.Common.PropertyItem("BJ_tpcode", "Mesnac.Entity.Eqm_bjsparecd");
            
            protected NBear.Common.PropertyItem _High_reserve = new NBear.Common.PropertyItem("High_reserve", "Mesnac.Entity.Eqm_bjsparecd");
            
            protected NBear.Common.PropertyItem _Low_reserve = new NBear.Common.PropertyItem("Low_reserve", "Mesnac.Entity.Eqm_bjsparecd");
            
            protected NBear.Common.PropertyItem _Order_point = new NBear.Common.PropertyItem("Order_point", "Mesnac.Entity.Eqm_bjsparecd");
            
            protected NBear.Common.PropertyItem _High_fund = new NBear.Common.PropertyItem("High_fund", "Mesnac.Entity.Eqm_bjsparecd");
            
            protected NBear.Common.PropertyItem _Low_fund = new NBear.Common.PropertyItem("Low_fund", "Mesnac.Entity.Eqm_bjsparecd");
            
            protected NBear.Common.PropertyItem _Pos_code = new NBear.Common.PropertyItem("Pos_code", "Mesnac.Entity.Eqm_bjsparecd");
            
            protected NBear.Common.PropertyItem _Plan_price = new NBear.Common.PropertyItem("Plan_price", "Mesnac.Entity.Eqm_bjsparecd");
            
            protected NBear.Common.PropertyItem _BJ_Class = new NBear.Common.PropertyItem("BJ_Class", "Mesnac.Entity.Eqm_bjsparecd");
            
            protected NBear.Common.PropertyItem _Memo = new NBear.Common.PropertyItem("Memo", "Mesnac.Entity.Eqm_bjsparecd");
            
            public @__Columns() {
            }
            
            public @__Columns(string aliasName) {
                this.aliasName = aliasName;
            }
            
            public NBear.Common.PropertyItem BJ_code {
                get {
                    if ((aliasName == null)) {
                        return _BJ_code;
                    }
                    else {
                        return new NBear.Common.PropertyItem("BJ_code", _BJ_code.EntityConfiguration, _BJ_code.PropertyConfiguration, aliasName);
                    }
                }
            }
            
            public NBear.Common.PropertyItem BJ_specType {
                get {
                    if ((aliasName == null)) {
                        return _BJ_specType;
                    }
                    else {
                        return new NBear.Common.PropertyItem("BJ_specType", _BJ_specType.EntityConfiguration, _BJ_specType.PropertyConfiguration, aliasName);
                    }
                }
            }
            
            public NBear.Common.PropertyItem BJ_name {
                get {
                    if ((aliasName == null)) {
                        return _BJ_name;
                    }
                    else {
                        return new NBear.Common.PropertyItem("BJ_name", _BJ_name.EntityConfiguration, _BJ_name.PropertyConfiguration, aliasName);
                    }
                }
            }
            
            public NBear.Common.PropertyItem Unit_name {
                get {
                    if ((aliasName == null)) {
                        return _Unit_name;
                    }
                    else {
                        return new NBear.Common.PropertyItem("Unit_name", _Unit_name.EntityConfiguration, _Unit_name.PropertyConfiguration, aliasName);
                    }
                }
            }
            
            public NBear.Common.PropertyItem BJ_tpcode {
                get {
                    if ((aliasName == null)) {
                        return _BJ_tpcode;
                    }
                    else {
                        return new NBear.Common.PropertyItem("BJ_tpcode", _BJ_tpcode.EntityConfiguration, _BJ_tpcode.PropertyConfiguration, aliasName);
                    }
                }
            }
            
            public NBear.Common.PropertyItem High_reserve {
                get {
                    if ((aliasName == null)) {
                        return _High_reserve;
                    }
                    else {
                        return new NBear.Common.PropertyItem("High_reserve", _High_reserve.EntityConfiguration, _High_reserve.PropertyConfiguration, aliasName);
                    }
                }
            }
            
            public NBear.Common.PropertyItem Low_reserve {
                get {
                    if ((aliasName == null)) {
                        return _Low_reserve;
                    }
                    else {
                        return new NBear.Common.PropertyItem("Low_reserve", _Low_reserve.EntityConfiguration, _Low_reserve.PropertyConfiguration, aliasName);
                    }
                }
            }
            
            public NBear.Common.PropertyItem Order_point {
                get {
                    if ((aliasName == null)) {
                        return _Order_point;
                    }
                    else {
                        return new NBear.Common.PropertyItem("Order_point", _Order_point.EntityConfiguration, _Order_point.PropertyConfiguration, aliasName);
                    }
                }
            }
            
            public NBear.Common.PropertyItem High_fund {
                get {
                    if ((aliasName == null)) {
                        return _High_fund;
                    }
                    else {
                        return new NBear.Common.PropertyItem("High_fund", _High_fund.EntityConfiguration, _High_fund.PropertyConfiguration, aliasName);
                    }
                }
            }
            
            public NBear.Common.PropertyItem Low_fund {
                get {
                    if ((aliasName == null)) {
                        return _Low_fund;
                    }
                    else {
                        return new NBear.Common.PropertyItem("Low_fund", _Low_fund.EntityConfiguration, _Low_fund.PropertyConfiguration, aliasName);
                    }
                }
            }
            
            public NBear.Common.PropertyItem Pos_code {
                get {
                    if ((aliasName == null)) {
                        return _Pos_code;
                    }
                    else {
                        return new NBear.Common.PropertyItem("Pos_code", _Pos_code.EntityConfiguration, _Pos_code.PropertyConfiguration, aliasName);
                    }
                }
            }
            
            public NBear.Common.PropertyItem Plan_price {
                get {
                    if ((aliasName == null)) {
                        return _Plan_price;
                    }
                    else {
                        return new NBear.Common.PropertyItem("Plan_price", _Plan_price.EntityConfiguration, _Plan_price.PropertyConfiguration, aliasName);
                    }
                }
            }
            
            public NBear.Common.PropertyItem BJ_Class {
                get {
                    if ((aliasName == null)) {
                        return _BJ_Class;
                    }
                    else {
                        return new NBear.Common.PropertyItem("BJ_Class", _BJ_Class.EntityConfiguration, _BJ_Class.PropertyConfiguration, aliasName);
                    }
                }
            }
            
            public NBear.Common.PropertyItem Memo {
                get {
                    if ((aliasName == null)) {
                        return _Memo;
                    }
                    else {
                        return new NBear.Common.PropertyItem("Memo", _Memo.EntityConfiguration, _Memo.PropertyConfiguration, aliasName);
                    }
                }
            }
        }
    }
}
